ALTER TABLE tenants ADD COLUMN IF NOT EXISTS knowledge_base TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS auto_reply_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS kind TEXT;
